services:
  mongodb:
    image: mongo:5.0
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - mongodb_data:/data/db
    restart: always

  data-loader:
    build: . 
    depends_on:
      mongodb:
        condition: service_started
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: sensor_database

volumes:
  mongodb_data: